/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module bank_scheduler(clk, rst_n, grant_valid, grant_addr, grant_data, grant_strobe, grant_we, grant_id, grant_ready, sram_we, sram_addr, sram_wdata, sram_bwe, sram_rdata, pp1_valid, pp1_rdata, pp1_id, pp1_we, pp1_err, bank_pp1_ready);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input grant_valid;
  wire grant_valid;
  input [9:0] grant_addr;
  wire [9:0] grant_addr;
  input [31:0] grant_data;
  wire [31:0] grant_data;
  input [3:0] grant_strobe;
  wire [3:0] grant_strobe;
  input grant_we;
  wire grant_we;
  input [5:0] grant_id;
  wire [5:0] grant_id;
  output grant_ready;
  wire grant_ready;
  output sram_we;
  wire sram_we;
  output [7:0] sram_addr;
  wire [7:0] sram_addr;
  output [31:0] sram_wdata;
  wire [31:0] sram_wdata;
  output [3:0] sram_bwe;
  wire [3:0] sram_bwe;
  input [31:0] sram_rdata;
  wire [31:0] sram_rdata;
  output pp1_valid;
  wire pp1_valid;
  output [31:0] pp1_rdata;
  wire [31:0] pp1_rdata;
  output [5:0] pp1_id;
  wire [5:0] pp1_id;
  output pp1_we;
  wire pp1_we;
  output pp1_err;
  wire pp1_err;
  input bank_pp1_ready;
  wire bank_pp1_ready;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire [5:0] pp0_id;
  wire [3:0] pp0_strobe;
  wire pp0_valid;
  wire pp0_we;
  sky130_fd_sc_hd__clkinv_1 _005_ (
    .A(bank_pp1_ready),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_0 _006_ (
    .A(pp0_valid),
    .B(pp0_we),
    .X(sram_we)
  );
  sky130_fd_sc_hd__and3_1 _007_ (
    .A(pp0_strobe[1]),
    .B(pp0_valid),
    .C(pp0_we),
    .X(sram_bwe[1])
  );
  sky130_fd_sc_hd__and3_1 _008_ (
    .A(pp0_strobe[0]),
    .B(pp0_valid),
    .C(pp0_we),
    .X(sram_bwe[0])
  );
  sky130_fd_sc_hd__nand3b_1 _009_ (
    .A_N(bank_pp1_ready),
    .B(pp1_valid),
    .C(pp0_valid),
    .Y(grant_ready)
  );
  sky130_fd_sc_hd__and2_0 _010_ (
    .A(rst_n),
    .B(grant_ready),
    .X(_000_)
  );
  sky130_fd_sc_hd__a21boi_0 _011_ (
    .A1(pp1_valid),
    .A2(_004_),
    .B1_N(rst_n),
    .Y(_001_)
  );
  sky130_fd_sc_hd__and3_1 _012_ (
    .A(pp0_strobe[3]),
    .B(pp0_valid),
    .C(pp0_we),
    .X(sram_bwe[3])
  );
  sky130_fd_sc_hd__and3_1 _013_ (
    .A(pp0_strobe[2]),
    .B(pp0_valid),
    .C(pp0_we),
    .X(sram_bwe[2])
  );
  sky130_fd_sc_hd__a21o_1 _014_ (
    .A1(pp1_valid),
    .A2(_004_),
    .B1(pp0_valid),
    .X(_002_)
  );
  sky130_fd_sc_hd__nand2b_1 _015_ (
    .A_N(grant_valid),
    .B(grant_ready),
    .Y(_003_)
  );
  sky130_fd_sc_hd__edfxtp_1 _016_ (
    .CLK(clk),
    .D(sram_rdata[0]),
    .DE(_001_),
    .Q(pp1_rdata[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _017_ (
    .CLK(clk),
    .D(sram_rdata[1]),
    .DE(_001_),
    .Q(pp1_rdata[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _018_ (
    .CLK(clk),
    .D(sram_rdata[2]),
    .DE(_001_),
    .Q(pp1_rdata[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _019_ (
    .CLK(clk),
    .D(sram_rdata[3]),
    .DE(_001_),
    .Q(pp1_rdata[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _020_ (
    .CLK(clk),
    .D(sram_rdata[4]),
    .DE(_001_),
    .Q(pp1_rdata[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _021_ (
    .CLK(clk),
    .D(sram_rdata[5]),
    .DE(_001_),
    .Q(pp1_rdata[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _022_ (
    .CLK(clk),
    .D(sram_rdata[6]),
    .DE(_001_),
    .Q(pp1_rdata[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _023_ (
    .CLK(clk),
    .D(sram_rdata[7]),
    .DE(_001_),
    .Q(pp1_rdata[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _024_ (
    .CLK(clk),
    .D(sram_rdata[8]),
    .DE(_001_),
    .Q(pp1_rdata[8])
  );
  sky130_fd_sc_hd__edfxtp_1 _025_ (
    .CLK(clk),
    .D(sram_rdata[9]),
    .DE(_001_),
    .Q(pp1_rdata[9])
  );
  sky130_fd_sc_hd__edfxtp_1 _026_ (
    .CLK(clk),
    .D(sram_rdata[10]),
    .DE(_001_),
    .Q(pp1_rdata[10])
  );
  sky130_fd_sc_hd__edfxtp_1 _027_ (
    .CLK(clk),
    .D(sram_rdata[11]),
    .DE(_001_),
    .Q(pp1_rdata[11])
  );
  sky130_fd_sc_hd__edfxtp_1 _028_ (
    .CLK(clk),
    .D(sram_rdata[12]),
    .DE(_001_),
    .Q(pp1_rdata[12])
  );
  sky130_fd_sc_hd__edfxtp_1 _029_ (
    .CLK(clk),
    .D(sram_rdata[13]),
    .DE(_001_),
    .Q(pp1_rdata[13])
  );
  sky130_fd_sc_hd__edfxtp_1 _030_ (
    .CLK(clk),
    .D(sram_rdata[14]),
    .DE(_001_),
    .Q(pp1_rdata[14])
  );
  sky130_fd_sc_hd__edfxtp_1 _031_ (
    .CLK(clk),
    .D(sram_rdata[15]),
    .DE(_001_),
    .Q(pp1_rdata[15])
  );
  sky130_fd_sc_hd__edfxtp_1 _032_ (
    .CLK(clk),
    .D(sram_rdata[16]),
    .DE(_001_),
    .Q(pp1_rdata[16])
  );
  sky130_fd_sc_hd__edfxtp_1 _033_ (
    .CLK(clk),
    .D(sram_rdata[17]),
    .DE(_001_),
    .Q(pp1_rdata[17])
  );
  sky130_fd_sc_hd__edfxtp_1 _034_ (
    .CLK(clk),
    .D(sram_rdata[18]),
    .DE(_001_),
    .Q(pp1_rdata[18])
  );
  sky130_fd_sc_hd__edfxtp_1 _035_ (
    .CLK(clk),
    .D(sram_rdata[19]),
    .DE(_001_),
    .Q(pp1_rdata[19])
  );
  sky130_fd_sc_hd__edfxtp_1 _036_ (
    .CLK(clk),
    .D(sram_rdata[20]),
    .DE(_001_),
    .Q(pp1_rdata[20])
  );
  sky130_fd_sc_hd__edfxtp_1 _037_ (
    .CLK(clk),
    .D(sram_rdata[21]),
    .DE(_001_),
    .Q(pp1_rdata[21])
  );
  sky130_fd_sc_hd__edfxtp_1 _038_ (
    .CLK(clk),
    .D(sram_rdata[22]),
    .DE(_001_),
    .Q(pp1_rdata[22])
  );
  sky130_fd_sc_hd__edfxtp_1 _039_ (
    .CLK(clk),
    .D(sram_rdata[23]),
    .DE(_001_),
    .Q(pp1_rdata[23])
  );
  sky130_fd_sc_hd__edfxtp_1 _040_ (
    .CLK(clk),
    .D(sram_rdata[24]),
    .DE(_001_),
    .Q(pp1_rdata[24])
  );
  sky130_fd_sc_hd__edfxtp_1 _041_ (
    .CLK(clk),
    .D(sram_rdata[25]),
    .DE(_001_),
    .Q(pp1_rdata[25])
  );
  sky130_fd_sc_hd__edfxtp_1 _042_ (
    .CLK(clk),
    .D(sram_rdata[26]),
    .DE(_001_),
    .Q(pp1_rdata[26])
  );
  sky130_fd_sc_hd__edfxtp_1 _043_ (
    .CLK(clk),
    .D(sram_rdata[27]),
    .DE(_001_),
    .Q(pp1_rdata[27])
  );
  sky130_fd_sc_hd__edfxtp_1 _044_ (
    .CLK(clk),
    .D(sram_rdata[28]),
    .DE(_001_),
    .Q(pp1_rdata[28])
  );
  sky130_fd_sc_hd__edfxtp_1 _045_ (
    .CLK(clk),
    .D(sram_rdata[29]),
    .DE(_001_),
    .Q(pp1_rdata[29])
  );
  sky130_fd_sc_hd__edfxtp_1 _046_ (
    .CLK(clk),
    .D(sram_rdata[30]),
    .DE(_001_),
    .Q(pp1_rdata[30])
  );
  sky130_fd_sc_hd__edfxtp_1 _047_ (
    .CLK(clk),
    .D(sram_rdata[31]),
    .DE(_001_),
    .Q(pp1_rdata[31])
  );
  sky130_fd_sc_hd__dfrtp_1 _048_ (
    .CLK(clk),
    .D(_002_),
    .Q(pp1_valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__edfxtp_1 _049_ (
    .CLK(clk),
    .D(grant_strobe[0]),
    .DE(_000_),
    .Q(pp0_strobe[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _050_ (
    .CLK(clk),
    .D(grant_strobe[1]),
    .DE(_000_),
    .Q(pp0_strobe[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _051_ (
    .CLK(clk),
    .D(grant_strobe[2]),
    .DE(_000_),
    .Q(pp0_strobe[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _052_ (
    .CLK(clk),
    .D(grant_strobe[3]),
    .DE(_000_),
    .Q(pp0_strobe[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _053_ (
    .CLK(clk),
    .D(grant_addr[2]),
    .DE(_000_),
    .Q(sram_addr[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _054_ (
    .CLK(clk),
    .D(grant_addr[3]),
    .DE(_000_),
    .Q(sram_addr[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _055_ (
    .CLK(clk),
    .D(grant_addr[4]),
    .DE(_000_),
    .Q(sram_addr[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _056_ (
    .CLK(clk),
    .D(grant_addr[5]),
    .DE(_000_),
    .Q(sram_addr[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _057_ (
    .CLK(clk),
    .D(grant_addr[6]),
    .DE(_000_),
    .Q(sram_addr[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _058_ (
    .CLK(clk),
    .D(grant_addr[7]),
    .DE(_000_),
    .Q(sram_addr[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _059_ (
    .CLK(clk),
    .D(grant_addr[8]),
    .DE(_000_),
    .Q(sram_addr[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _060_ (
    .CLK(clk),
    .D(grant_addr[9]),
    .DE(_000_),
    .Q(sram_addr[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _061_ (
    .CLK(clk),
    .D(grant_data[0]),
    .DE(_000_),
    .Q(sram_wdata[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _062_ (
    .CLK(clk),
    .D(grant_data[1]),
    .DE(_000_),
    .Q(sram_wdata[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _063_ (
    .CLK(clk),
    .D(grant_data[2]),
    .DE(_000_),
    .Q(sram_wdata[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _064_ (
    .CLK(clk),
    .D(grant_data[3]),
    .DE(_000_),
    .Q(sram_wdata[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _065_ (
    .CLK(clk),
    .D(grant_data[4]),
    .DE(_000_),
    .Q(sram_wdata[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _066_ (
    .CLK(clk),
    .D(grant_data[5]),
    .DE(_000_),
    .Q(sram_wdata[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _067_ (
    .CLK(clk),
    .D(grant_data[6]),
    .DE(_000_),
    .Q(sram_wdata[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _068_ (
    .CLK(clk),
    .D(grant_data[7]),
    .DE(_000_),
    .Q(sram_wdata[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _069_ (
    .CLK(clk),
    .D(grant_data[8]),
    .DE(_000_),
    .Q(sram_wdata[8])
  );
  sky130_fd_sc_hd__edfxtp_1 _070_ (
    .CLK(clk),
    .D(grant_data[9]),
    .DE(_000_),
    .Q(sram_wdata[9])
  );
  sky130_fd_sc_hd__edfxtp_1 _071_ (
    .CLK(clk),
    .D(grant_data[10]),
    .DE(_000_),
    .Q(sram_wdata[10])
  );
  sky130_fd_sc_hd__edfxtp_1 _072_ (
    .CLK(clk),
    .D(grant_data[11]),
    .DE(_000_),
    .Q(sram_wdata[11])
  );
  sky130_fd_sc_hd__edfxtp_1 _073_ (
    .CLK(clk),
    .D(grant_data[12]),
    .DE(_000_),
    .Q(sram_wdata[12])
  );
  sky130_fd_sc_hd__edfxtp_1 _074_ (
    .CLK(clk),
    .D(grant_data[13]),
    .DE(_000_),
    .Q(sram_wdata[13])
  );
  sky130_fd_sc_hd__edfxtp_1 _075_ (
    .CLK(clk),
    .D(grant_data[14]),
    .DE(_000_),
    .Q(sram_wdata[14])
  );
  sky130_fd_sc_hd__edfxtp_1 _076_ (
    .CLK(clk),
    .D(grant_data[15]),
    .DE(_000_),
    .Q(sram_wdata[15])
  );
  sky130_fd_sc_hd__edfxtp_1 _077_ (
    .CLK(clk),
    .D(grant_data[16]),
    .DE(_000_),
    .Q(sram_wdata[16])
  );
  sky130_fd_sc_hd__edfxtp_1 _078_ (
    .CLK(clk),
    .D(grant_data[17]),
    .DE(_000_),
    .Q(sram_wdata[17])
  );
  sky130_fd_sc_hd__edfxtp_1 _079_ (
    .CLK(clk),
    .D(grant_data[18]),
    .DE(_000_),
    .Q(sram_wdata[18])
  );
  sky130_fd_sc_hd__edfxtp_1 _080_ (
    .CLK(clk),
    .D(grant_data[19]),
    .DE(_000_),
    .Q(sram_wdata[19])
  );
  sky130_fd_sc_hd__edfxtp_1 _081_ (
    .CLK(clk),
    .D(grant_data[20]),
    .DE(_000_),
    .Q(sram_wdata[20])
  );
  sky130_fd_sc_hd__edfxtp_1 _082_ (
    .CLK(clk),
    .D(grant_data[21]),
    .DE(_000_),
    .Q(sram_wdata[21])
  );
  sky130_fd_sc_hd__edfxtp_1 _083_ (
    .CLK(clk),
    .D(grant_data[22]),
    .DE(_000_),
    .Q(sram_wdata[22])
  );
  sky130_fd_sc_hd__edfxtp_1 _084_ (
    .CLK(clk),
    .D(grant_data[23]),
    .DE(_000_),
    .Q(sram_wdata[23])
  );
  sky130_fd_sc_hd__edfxtp_1 _085_ (
    .CLK(clk),
    .D(grant_data[24]),
    .DE(_000_),
    .Q(sram_wdata[24])
  );
  sky130_fd_sc_hd__edfxtp_1 _086_ (
    .CLK(clk),
    .D(grant_data[25]),
    .DE(_000_),
    .Q(sram_wdata[25])
  );
  sky130_fd_sc_hd__edfxtp_1 _087_ (
    .CLK(clk),
    .D(grant_data[26]),
    .DE(_000_),
    .Q(sram_wdata[26])
  );
  sky130_fd_sc_hd__edfxtp_1 _088_ (
    .CLK(clk),
    .D(grant_data[27]),
    .DE(_000_),
    .Q(sram_wdata[27])
  );
  sky130_fd_sc_hd__edfxtp_1 _089_ (
    .CLK(clk),
    .D(grant_data[28]),
    .DE(_000_),
    .Q(sram_wdata[28])
  );
  sky130_fd_sc_hd__edfxtp_1 _090_ (
    .CLK(clk),
    .D(grant_data[29]),
    .DE(_000_),
    .Q(sram_wdata[29])
  );
  sky130_fd_sc_hd__edfxtp_1 _091_ (
    .CLK(clk),
    .D(grant_data[30]),
    .DE(_000_),
    .Q(sram_wdata[30])
  );
  sky130_fd_sc_hd__edfxtp_1 _092_ (
    .CLK(clk),
    .D(grant_data[31]),
    .DE(_000_),
    .Q(sram_wdata[31])
  );
  sky130_fd_sc_hd__edfxtp_1 _093_ (
    .CLK(clk),
    .D(grant_id[0]),
    .DE(_000_),
    .Q(pp0_id[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _094_ (
    .CLK(clk),
    .D(grant_id[1]),
    .DE(_000_),
    .Q(pp0_id[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _095_ (
    .CLK(clk),
    .D(grant_id[2]),
    .DE(_000_),
    .Q(pp0_id[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _096_ (
    .CLK(clk),
    .D(grant_id[3]),
    .DE(_000_),
    .Q(pp0_id[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _097_ (
    .CLK(clk),
    .D(grant_id[4]),
    .DE(_000_),
    .Q(pp0_id[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _098_ (
    .CLK(clk),
    .D(grant_id[5]),
    .DE(_000_),
    .Q(pp0_id[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _099_ (
    .CLK(clk),
    .D(pp0_id[0]),
    .DE(_001_),
    .Q(pp1_id[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _100_ (
    .CLK(clk),
    .D(pp0_id[1]),
    .DE(_001_),
    .Q(pp1_id[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _101_ (
    .CLK(clk),
    .D(pp0_id[2]),
    .DE(_001_),
    .Q(pp1_id[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _102_ (
    .CLK(clk),
    .D(pp0_id[3]),
    .DE(_001_),
    .Q(pp1_id[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _103_ (
    .CLK(clk),
    .D(pp0_id[4]),
    .DE(_001_),
    .Q(pp1_id[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _104_ (
    .CLK(clk),
    .D(pp0_id[5]),
    .DE(_001_),
    .Q(pp1_id[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _105_ (
    .CLK(clk),
    .D(pp0_we),
    .DE(_001_),
    .Q(pp1_we)
  );
  sky130_fd_sc_hd__edfxtp_1 _106_ (
    .CLK(clk),
    .D(grant_we),
    .DE(_000_),
    .Q(pp0_we)
  );
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk),
    .D(_003_),
    .Q(pp0_valid),
    .RESET_B(rst_n)
  );
  assign pp1_err = 1'h0;
endmodule
