/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module per_bank_arb(clk, rst_n, req_valid, grant_valid, grant_port, grant_ready, conflict_mask);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input [3:0] req_valid;
  wire [3:0] req_valid;
  output grant_valid;
  wire grant_valid;
  output [1:0] grant_port;
  wire [1:0] grant_port;
  input grant_ready;
  wire grant_ready;
  output [3:0] conflict_mask;
  wire [3:0] conflict_mask;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire [1:0] ptr;
  sky130_fd_sc_hd__clkinv_1 _33_ (
    .A(req_valid[2]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _34_ (
    .A(req_valid[1]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _35_ (
    .A(req_valid[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__clkinv_1 _36_ (
    .A(ptr[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _37_ (
    .A(ptr[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__clkinv_1 _38_ (
    .A(req_valid[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__mux4_2 _39_ (
    .A0(req_valid[0]),
    .A1(req_valid[1]),
    .A2(req_valid[2]),
    .A3(req_valid[3]),
    .S0(ptr[0]),
    .S1(ptr[1]),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux4_2 _40_ (
    .A0(req_valid[1]),
    .A1(req_valid[3]),
    .A2(req_valid[2]),
    .A3(req_valid[0]),
    .S0(ptr[1]),
    .S1(ptr[0]),
    .X(_09_)
  );
  sky130_fd_sc_hd__mux4_2 _41_ (
    .A0(req_valid[2]),
    .A1(req_valid[0]),
    .A2(req_valid[3]),
    .A3(req_valid[1]),
    .S0(ptr[1]),
    .S1(ptr[0]),
    .X(_10_)
  );
  sky130_fd_sc_hd__mux4_2 _42_ (
    .A0(req_valid[3]),
    .A1(req_valid[0]),
    .A2(req_valid[1]),
    .A3(req_valid[2]),
    .S0(ptr[0]),
    .S1(ptr[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__or4b_1 _43_ (
    .A(_08_),
    .B(_09_),
    .C(_10_),
    .D_N(_11_),
    .X(_12_)
  );
  sky130_fd_sc_hd__or3b_1 _44_ (
    .A(_08_),
    .B(_09_),
    .C_N(_10_),
    .X(_13_)
  );
  sky130_fd_sc_hd__mux2i_1 _45_ (
    .A0(_12_),
    .A1(_13_),
    .S(ptr[0]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand2b_1 _46_ (
    .A_N(_08_),
    .B(_09_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _47_ (
    .A(ptr[0]),
    .B(_08_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__o21ai_0 _48_ (
    .A1(ptr[0]),
    .A2(_15_),
    .B1(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__mux4_2 _49_ (
    .A0(_07_),
    .A1(_13_),
    .A2(_15_),
    .A3(_12_),
    .S0(_06_),
    .S1(_05_),
    .X(_18_)
  );
  sky130_fd_sc_hd__nand2_1 _50_ (
    .A(_05_),
    .B(_13_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__nand2_1 _51_ (
    .A(ptr[0]),
    .B(_15_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _52_ (
    .A(ptr[0]),
    .B(_08_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__mux4_2 _53_ (
    .A0(_02_),
    .A1(_12_),
    .A2(_13_),
    .A3(_15_),
    .S0(ptr[0]),
    .S1(_06_),
    .X(_22_)
  );
  sky130_fd_sc_hd__nand2_1 _54_ (
    .A(_18_),
    .B(_22_),
    .Y(grant_port[1])
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _55_ (
    .A(_14_),
    .SLEEP(_17_),
    .X(grant_port[0])
  );
  sky130_fd_sc_hd__and2_0 _56_ (
    .A(req_valid[2]),
    .B(_22_),
    .X(conflict_mask[2])
  );
  sky130_fd_sc_hd__mux4_2 _57_ (
    .A0(_03_),
    .A1(_13_),
    .A2(_15_),
    .A3(_12_),
    .S0(ptr[1]),
    .S1(_05_),
    .X(_23_)
  );
  sky130_fd_sc_hd__and2_0 _58_ (
    .A(req_valid[1]),
    .B(_23_),
    .X(conflict_mask[1])
  );
  sky130_fd_sc_hd__a211oi_1 _59_ (
    .A1(ptr[0]),
    .A2(_12_),
    .B1(_21_),
    .C1(ptr[1]),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a311oi_1 _60_ (
    .A1(ptr[1]),
    .A2(_19_),
    .A3(_20_),
    .B1(_24_),
    .C1(_04_),
    .Y(conflict_mask[0])
  );
  sky130_fd_sc_hd__or4_1 _61_ (
    .A(_08_),
    .B(_09_),
    .C(_10_),
    .D(_11_),
    .X(grant_valid)
  );
  sky130_fd_sc_hd__a211oi_1 _62_ (
    .A1(req_valid[2]),
    .A2(req_valid[1]),
    .B1(req_valid[0]),
    .C1(req_valid[3]),
    .Y(_25_)
  );
  sky130_fd_sc_hd__o21ai_0 _63_ (
    .A1(req_valid[2]),
    .A2(req_valid[1]),
    .B1(_25_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a211oi_1 _64_ (
    .A1(req_valid[0]),
    .A2(req_valid[3]),
    .B1(req_valid[2]),
    .C1(req_valid[1]),
    .Y(_27_)
  );
  sky130_fd_sc_hd__o21ai_0 _65_ (
    .A1(req_valid[0]),
    .A2(req_valid[3]),
    .B1(_27_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__and4_1 _66_ (
    .A(grant_ready),
    .B(grant_valid),
    .C(_26_),
    .D(_28_),
    .X(_29_)
  );
  sky130_fd_sc_hd__nand4_1 _67_ (
    .A(grant_ready),
    .B(grant_valid),
    .C(_26_),
    .D(_28_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__a41o_1 _68_ (
    .A1(grant_ready),
    .A2(grant_valid),
    .A3(_26_),
    .A4(_28_),
    .B1(_05_),
    .X(_31_)
  );
  sky130_fd_sc_hd__o31ai_1 _69_ (
    .A1(_14_),
    .A2(_17_),
    .A3(_30_),
    .B1(_31_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__and2_0 _70_ (
    .A(req_valid[3]),
    .B(_18_),
    .X(conflict_mask[3])
  );
  sky130_fd_sc_hd__a41oi_1 _71_ (
    .A1(grant_ready),
    .A2(grant_valid),
    .A3(_26_),
    .A4(_28_),
    .B1(ptr[1]),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a31oi_1 _72_ (
    .A1(_22_),
    .A2(_23_),
    .A3(_29_),
    .B1(_32_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__dfrtp_1 _73_ (
    .CLK(clk),
    .D(_00_),
    .Q(ptr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _74_ (
    .CLK(clk),
    .D(_01_),
    .Q(ptr[1]),
    .RESET_B(rst_n)
  );
endmodule
