/* Generated by Yosys 0.67+post (git sha1 b8e7da6f40ae8f552c116bf6c359b07c6533e159, Release, AppleClang clang++ 21.0.0.21000099) */

module rsp_fifo(clk, rst_n, push_valid, push_ready, push_data, pop_valid, pop_ready, pop_data, full, empty);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input push_valid;
  wire push_valid;
  output push_ready;
  wire push_ready;
  input [63:0] push_data;
  wire [63:0] push_data;
  output pop_valid;
  wire pop_valid;
  input pop_ready;
  wire pop_ready;
  output [63:0] pop_data;
  wire [63:0] pop_data;
  output full;
  wire full;
  output empty;
  wire empty;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire [63:0] \fifo_mem[0] ;
  wire [63:0] \fifo_mem[1] ;
  wire [63:0] \fifo_mem[2] ;
  wire [63:0] \fifo_mem[3] ;
  wire [2:0] occupancy;
  wire [1:0] rd_ptr;
  wire [1:0] wr_ptr;
  sky130_fd_sc_hd__clkinv_1 _157_ (
    .A(occupancy[2]),
    .Y(push_ready)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _159_ (
    .A(rd_ptr[0]),
    .SLEEP(rd_ptr[1]),
    .X(_012_)
  );
  sky130_fd_sc_hd__and2_0 _160_ (
    .A(rd_ptr[1]),
    .B(rd_ptr[0]),
    .X(_013_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _161_ (
    .A(rd_ptr[1]),
    .SLEEP(rd_ptr[0]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _162_ (
    .A(\fifo_mem[2] [62]),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a222oi_1 _163_ (
    .A1(\fifo_mem[0] [62]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [62]),
    .C1(_013_),
    .C2(\fifo_mem[3] [62]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_015_),
    .B(_016_),
    .Y(pop_data[62])
  );
  sky130_fd_sc_hd__nand2_1 _165_ (
    .A(\fifo_mem[3] [61]),
    .B(_013_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a222oi_1 _166_ (
    .A1(\fifo_mem[0] [61]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [61]),
    .C1(_014_),
    .C2(\fifo_mem[2] [61]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_017_),
    .B(_018_),
    .Y(pop_data[61])
  );
  sky130_fd_sc_hd__nand2_1 _168_ (
    .A(\fifo_mem[1] [60]),
    .B(_012_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a222oi_1 _169_ (
    .A1(\fifo_mem[0] [60]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [60]),
    .C1(_014_),
    .C2(\fifo_mem[2] [60]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _170_ (
    .A(_019_),
    .B(_020_),
    .Y(pop_data[60])
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(\fifo_mem[3] [59]),
    .B(_013_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__a222oi_1 _172_ (
    .A1(\fifo_mem[0] [59]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [59]),
    .C1(_014_),
    .C2(\fifo_mem[2] [59]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(_021_),
    .B(_022_),
    .Y(pop_data[59])
  );
  sky130_fd_sc_hd__nand2_1 _174_ (
    .A(\fifo_mem[1] [58]),
    .B(_012_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a222oi_1 _175_ (
    .A1(\fifo_mem[0] [58]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [58]),
    .C1(_014_),
    .C2(\fifo_mem[2] [58]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _176_ (
    .A(_023_),
    .B(_024_),
    .Y(pop_data[58])
  );
  sky130_fd_sc_hd__nand2_1 _177_ (
    .A(\fifo_mem[1] [57]),
    .B(_012_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a222oi_1 _178_ (
    .A1(\fifo_mem[0] [57]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [57]),
    .C1(_014_),
    .C2(\fifo_mem[2] [57]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand2_1 _179_ (
    .A(_025_),
    .B(_026_),
    .Y(pop_data[57])
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(\fifo_mem[3] [56]),
    .B(_013_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a222oi_1 _181_ (
    .A1(\fifo_mem[0] [56]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [56]),
    .C1(_014_),
    .C2(\fifo_mem[2] [56]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _182_ (
    .A(_027_),
    .B(_028_),
    .Y(pop_data[56])
  );
  sky130_fd_sc_hd__nand2_1 _183_ (
    .A(\fifo_mem[3] [55]),
    .B(_013_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a222oi_1 _184_ (
    .A1(\fifo_mem[0] [55]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [55]),
    .C1(_014_),
    .C2(\fifo_mem[2] [55]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _185_ (
    .A(_029_),
    .B(_030_),
    .Y(pop_data[55])
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(\fifo_mem[1] [54]),
    .B(_012_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a222oi_1 _187_ (
    .A1(\fifo_mem[0] [54]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [54]),
    .C1(_014_),
    .C2(\fifo_mem[2] [54]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_031_),
    .B(_032_),
    .Y(pop_data[54])
  );
  sky130_fd_sc_hd__nand2_1 _189_ (
    .A(\fifo_mem[3] [53]),
    .B(_013_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a222oi_1 _190_ (
    .A1(\fifo_mem[0] [53]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [53]),
    .C1(_014_),
    .C2(\fifo_mem[2] [53]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _191_ (
    .A(_033_),
    .B(_034_),
    .Y(pop_data[53])
  );
  sky130_fd_sc_hd__nand2_1 _192_ (
    .A(\fifo_mem[1] [52]),
    .B(_012_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a222oi_1 _193_ (
    .A1(\fifo_mem[0] [52]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [52]),
    .C1(_014_),
    .C2(\fifo_mem[2] [52]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand2_1 _194_ (
    .A(_035_),
    .B(_036_),
    .Y(pop_data[52])
  );
  sky130_fd_sc_hd__nand2_1 _195_ (
    .A(\fifo_mem[3] [51]),
    .B(_013_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a222oi_1 _196_ (
    .A1(\fifo_mem[0] [51]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [51]),
    .C1(_014_),
    .C2(\fifo_mem[2] [51]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nand2_1 _197_ (
    .A(_037_),
    .B(_038_),
    .Y(pop_data[51])
  );
  sky130_fd_sc_hd__nand2_1 _198_ (
    .A(\fifo_mem[1] [50]),
    .B(_012_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a222oi_1 _199_ (
    .A1(\fifo_mem[0] [50]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [50]),
    .C1(_014_),
    .C2(\fifo_mem[2] [50]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand2_1 _200_ (
    .A(_039_),
    .B(_040_),
    .Y(pop_data[50])
  );
  sky130_fd_sc_hd__nand2_1 _201_ (
    .A(\fifo_mem[1] [49]),
    .B(_012_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__a222oi_1 _202_ (
    .A1(\fifo_mem[0] [49]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [49]),
    .C1(_014_),
    .C2(\fifo_mem[2] [49]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand2_1 _203_ (
    .A(_041_),
    .B(_042_),
    .Y(pop_data[49])
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(\fifo_mem[3] [48]),
    .B(_013_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a222oi_1 _205_ (
    .A1(\fifo_mem[0] [48]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [48]),
    .C1(_014_),
    .C2(\fifo_mem[2] [48]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _206_ (
    .A(_043_),
    .B(_044_),
    .Y(pop_data[48])
  );
  sky130_fd_sc_hd__nand2_1 _207_ (
    .A(\fifo_mem[3] [47]),
    .B(_013_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__a222oi_1 _208_ (
    .A1(\fifo_mem[0] [47]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [47]),
    .C1(_014_),
    .C2(\fifo_mem[2] [47]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _209_ (
    .A(_045_),
    .B(_046_),
    .Y(pop_data[47])
  );
  sky130_fd_sc_hd__nand2_1 _210_ (
    .A(\fifo_mem[1] [46]),
    .B(_012_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a222oi_1 _211_ (
    .A1(\fifo_mem[0] [46]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [46]),
    .C1(_014_),
    .C2(\fifo_mem[2] [46]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _212_ (
    .A(_047_),
    .B(_048_),
    .Y(pop_data[46])
  );
  sky130_fd_sc_hd__nand2_1 _213_ (
    .A(\fifo_mem[3] [45]),
    .B(_013_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__a222oi_1 _214_ (
    .A1(\fifo_mem[0] [45]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [45]),
    .C1(_014_),
    .C2(\fifo_mem[2] [45]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_1 _215_ (
    .A(_049_),
    .B(_050_),
    .Y(pop_data[45])
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(\fifo_mem[1] [44]),
    .B(_012_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a222oi_1 _217_ (
    .A1(\fifo_mem[0] [44]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [44]),
    .C1(_014_),
    .C2(\fifo_mem[2] [44]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _218_ (
    .A(_051_),
    .B(_052_),
    .Y(pop_data[44])
  );
  sky130_fd_sc_hd__nand2_1 _219_ (
    .A(\fifo_mem[3] [43]),
    .B(_013_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__a222oi_1 _220_ (
    .A1(\fifo_mem[0] [43]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [43]),
    .C1(_014_),
    .C2(\fifo_mem[2] [43]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _221_ (
    .A(_053_),
    .B(_054_),
    .Y(pop_data[43])
  );
  sky130_fd_sc_hd__nand2_1 _222_ (
    .A(\fifo_mem[1] [42]),
    .B(_012_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a222oi_1 _223_ (
    .A1(\fifo_mem[0] [42]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [42]),
    .C1(_014_),
    .C2(\fifo_mem[2] [42]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_055_),
    .B(_056_),
    .Y(pop_data[42])
  );
  sky130_fd_sc_hd__nand2_1 _225_ (
    .A(\fifo_mem[1] [41]),
    .B(_012_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a222oi_1 _226_ (
    .A1(\fifo_mem[0] [41]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [41]),
    .C1(_014_),
    .C2(\fifo_mem[2] [41]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_057_),
    .B(_058_),
    .Y(pop_data[41])
  );
  sky130_fd_sc_hd__nand2_1 _228_ (
    .A(\fifo_mem[3] [40]),
    .B(_013_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a222oi_1 _229_ (
    .A1(\fifo_mem[0] [40]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [40]),
    .C1(_014_),
    .C2(\fifo_mem[2] [40]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand2_1 _230_ (
    .A(_059_),
    .B(_060_),
    .Y(pop_data[40])
  );
  sky130_fd_sc_hd__nand2_1 _231_ (
    .A(\fifo_mem[3] [39]),
    .B(_013_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__a222oi_1 _232_ (
    .A1(\fifo_mem[0] [39]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [39]),
    .C1(_014_),
    .C2(\fifo_mem[2] [39]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_061_),
    .B(_062_),
    .Y(pop_data[39])
  );
  sky130_fd_sc_hd__nand2_1 _234_ (
    .A(\fifo_mem[1] [38]),
    .B(_012_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a222oi_1 _235_ (
    .A1(\fifo_mem[0] [38]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [38]),
    .C1(_014_),
    .C2(\fifo_mem[2] [38]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2_1 _236_ (
    .A(_063_),
    .B(_064_),
    .Y(pop_data[38])
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(\fifo_mem[3] [37]),
    .B(_013_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__a222oi_1 _238_ (
    .A1(\fifo_mem[0] [37]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [37]),
    .C1(_014_),
    .C2(\fifo_mem[2] [37]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _239_ (
    .A(_065_),
    .B(_066_),
    .Y(pop_data[37])
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(\fifo_mem[1] [36]),
    .B(_012_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__a222oi_1 _241_ (
    .A1(\fifo_mem[0] [36]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [36]),
    .C1(_014_),
    .C2(\fifo_mem[2] [36]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand2_1 _242_ (
    .A(_067_),
    .B(_068_),
    .Y(pop_data[36])
  );
  sky130_fd_sc_hd__nand2_1 _243_ (
    .A(\fifo_mem[3] [35]),
    .B(_013_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__a222oi_1 _244_ (
    .A1(\fifo_mem[0] [35]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [35]),
    .C1(_014_),
    .C2(\fifo_mem[2] [35]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _245_ (
    .A(_069_),
    .B(_070_),
    .Y(pop_data[35])
  );
  sky130_fd_sc_hd__nand2_1 _246_ (
    .A(\fifo_mem[1] [34]),
    .B(_012_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__a222oi_1 _247_ (
    .A1(\fifo_mem[0] [34]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [34]),
    .C1(_014_),
    .C2(\fifo_mem[2] [34]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand2_1 _248_ (
    .A(_071_),
    .B(_072_),
    .Y(pop_data[34])
  );
  sky130_fd_sc_hd__nand2_1 _249_ (
    .A(\fifo_mem[1] [33]),
    .B(_012_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__a222oi_1 _250_ (
    .A1(\fifo_mem[0] [33]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [33]),
    .C1(_014_),
    .C2(\fifo_mem[2] [33]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _251_ (
    .A(_073_),
    .B(_074_),
    .Y(pop_data[33])
  );
  sky130_fd_sc_hd__nand2_1 _252_ (
    .A(\fifo_mem[3] [32]),
    .B(_013_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a222oi_1 _253_ (
    .A1(\fifo_mem[0] [32]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [32]),
    .C1(_014_),
    .C2(\fifo_mem[2] [32]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nand2_1 _254_ (
    .A(_075_),
    .B(_076_),
    .Y(pop_data[32])
  );
  sky130_fd_sc_hd__nand2_1 _255_ (
    .A(\fifo_mem[3] [31]),
    .B(_013_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__a222oi_1 _256_ (
    .A1(\fifo_mem[0] [31]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [31]),
    .C1(_014_),
    .C2(\fifo_mem[2] [31]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _257_ (
    .A(_077_),
    .B(_078_),
    .Y(pop_data[31])
  );
  sky130_fd_sc_hd__nand2_1 _258_ (
    .A(\fifo_mem[1] [30]),
    .B(_012_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__a222oi_1 _259_ (
    .A1(\fifo_mem[0] [30]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [30]),
    .C1(_014_),
    .C2(\fifo_mem[2] [30]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(_079_),
    .B(_080_),
    .Y(pop_data[30])
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(\fifo_mem[3] [29]),
    .B(_013_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__a222oi_1 _262_ (
    .A1(\fifo_mem[0] [29]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [29]),
    .C1(_014_),
    .C2(\fifo_mem[2] [29]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nand2_1 _263_ (
    .A(_081_),
    .B(_082_),
    .Y(pop_data[29])
  );
  sky130_fd_sc_hd__nand2_1 _264_ (
    .A(\fifo_mem[1] [28]),
    .B(_012_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__a222oi_1 _265_ (
    .A1(\fifo_mem[0] [28]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [28]),
    .C1(_014_),
    .C2(\fifo_mem[2] [28]),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nand2_1 _266_ (
    .A(_083_),
    .B(_084_),
    .Y(pop_data[28])
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(\fifo_mem[3] [27]),
    .B(_013_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a222oi_1 _268_ (
    .A1(\fifo_mem[0] [27]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [27]),
    .C1(_014_),
    .C2(\fifo_mem[2] [27]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _269_ (
    .A(_085_),
    .B(_086_),
    .Y(pop_data[27])
  );
  sky130_fd_sc_hd__nand2_1 _270_ (
    .A(\fifo_mem[1] [26]),
    .B(_012_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a222oi_1 _271_ (
    .A1(\fifo_mem[0] [26]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [26]),
    .C1(_014_),
    .C2(\fifo_mem[2] [26]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nand2_1 _272_ (
    .A(_087_),
    .B(_088_),
    .Y(pop_data[26])
  );
  sky130_fd_sc_hd__nand2_1 _273_ (
    .A(\fifo_mem[1] [25]),
    .B(_012_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__a222oi_1 _274_ (
    .A1(\fifo_mem[0] [25]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [25]),
    .C1(_014_),
    .C2(\fifo_mem[2] [25]),
    .Y(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _275_ (
    .A(_089_),
    .B(_090_),
    .Y(pop_data[25])
  );
  sky130_fd_sc_hd__nand2_1 _276_ (
    .A(\fifo_mem[3] [24]),
    .B(_013_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a222oi_1 _277_ (
    .A1(\fifo_mem[0] [24]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [24]),
    .C1(_014_),
    .C2(\fifo_mem[2] [24]),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand2_1 _278_ (
    .A(_091_),
    .B(_092_),
    .Y(pop_data[24])
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(\fifo_mem[3] [23]),
    .B(_013_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a222oi_1 _280_ (
    .A1(\fifo_mem[0] [23]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [23]),
    .C1(_014_),
    .C2(\fifo_mem[2] [23]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _281_ (
    .A(_093_),
    .B(_094_),
    .Y(pop_data[23])
  );
  sky130_fd_sc_hd__nand2_1 _282_ (
    .A(\fifo_mem[1] [22]),
    .B(_012_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a222oi_1 _283_ (
    .A1(\fifo_mem[0] [22]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [22]),
    .C1(_014_),
    .C2(\fifo_mem[2] [22]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_095_),
    .B(_096_),
    .Y(pop_data[22])
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(\fifo_mem[3] [21]),
    .B(_013_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__a222oi_1 _286_ (
    .A1(\fifo_mem[0] [21]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [21]),
    .C1(_014_),
    .C2(\fifo_mem[2] [21]),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_097_),
    .B(_098_),
    .Y(pop_data[21])
  );
  sky130_fd_sc_hd__nand2_1 _288_ (
    .A(\fifo_mem[1] [20]),
    .B(_012_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a222oi_1 _289_ (
    .A1(\fifo_mem[0] [20]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [20]),
    .C1(_014_),
    .C2(\fifo_mem[2] [20]),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nand2_1 _290_ (
    .A(_099_),
    .B(_100_),
    .Y(pop_data[20])
  );
  sky130_fd_sc_hd__nand2_1 _291_ (
    .A(\fifo_mem[3] [19]),
    .B(_013_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__a222oi_1 _292_ (
    .A1(\fifo_mem[0] [19]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [19]),
    .C1(_014_),
    .C2(\fifo_mem[2] [19]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(_101_),
    .B(_102_),
    .Y(pop_data[19])
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(\fifo_mem[1] [18]),
    .B(_012_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a222oi_1 _295_ (
    .A1(\fifo_mem[0] [18]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [18]),
    .C1(_014_),
    .C2(\fifo_mem[2] [18]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(_103_),
    .B(_104_),
    .Y(pop_data[18])
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(\fifo_mem[1] [17]),
    .B(_012_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__a222oi_1 _298_ (
    .A1(\fifo_mem[0] [17]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [17]),
    .C1(_014_),
    .C2(\fifo_mem[2] [17]),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand2_1 _299_ (
    .A(_105_),
    .B(_106_),
    .Y(pop_data[17])
  );
  sky130_fd_sc_hd__nand2_1 _300_ (
    .A(\fifo_mem[3] [16]),
    .B(_013_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a222oi_1 _301_ (
    .A1(\fifo_mem[0] [16]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [16]),
    .C1(_014_),
    .C2(\fifo_mem[2] [16]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(_107_),
    .B(_108_),
    .Y(pop_data[16])
  );
  sky130_fd_sc_hd__nand2_1 _303_ (
    .A(\fifo_mem[3] [15]),
    .B(_013_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a222oi_1 _304_ (
    .A1(\fifo_mem[0] [15]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [15]),
    .C1(_014_),
    .C2(\fifo_mem[2] [15]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _305_ (
    .A(_109_),
    .B(_110_),
    .Y(pop_data[15])
  );
  sky130_fd_sc_hd__nand2_1 _306_ (
    .A(\fifo_mem[1] [14]),
    .B(_012_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__a222oi_1 _307_ (
    .A1(\fifo_mem[0] [14]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [14]),
    .C1(_014_),
    .C2(\fifo_mem[2] [14]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nand2_1 _308_ (
    .A(_111_),
    .B(_112_),
    .Y(pop_data[14])
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(\fifo_mem[3] [13]),
    .B(_013_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a222oi_1 _310_ (
    .A1(\fifo_mem[0] [13]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [13]),
    .C1(_014_),
    .C2(\fifo_mem[2] [13]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand2_1 _311_ (
    .A(_113_),
    .B(_114_),
    .Y(pop_data[13])
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(\fifo_mem[1] [12]),
    .B(_012_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__a222oi_1 _313_ (
    .A1(\fifo_mem[0] [12]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [12]),
    .C1(_014_),
    .C2(\fifo_mem[2] [12]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(_115_),
    .B(_116_),
    .Y(pop_data[12])
  );
  sky130_fd_sc_hd__nand2_1 _315_ (
    .A(\fifo_mem[3] [11]),
    .B(_013_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a222oi_1 _316_ (
    .A1(\fifo_mem[0] [11]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [11]),
    .C1(_014_),
    .C2(\fifo_mem[2] [11]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _317_ (
    .A(_117_),
    .B(_118_),
    .Y(pop_data[11])
  );
  sky130_fd_sc_hd__nand2_1 _318_ (
    .A(\fifo_mem[1] [10]),
    .B(_012_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__a222oi_1 _319_ (
    .A1(\fifo_mem[0] [10]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [10]),
    .C1(_014_),
    .C2(\fifo_mem[2] [10]),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(_119_),
    .B(_120_),
    .Y(pop_data[10])
  );
  sky130_fd_sc_hd__nand2_1 _321_ (
    .A(\fifo_mem[1] [9]),
    .B(_012_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a222oi_1 _322_ (
    .A1(\fifo_mem[0] [9]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [9]),
    .C1(_014_),
    .C2(\fifo_mem[2] [9]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nand2_1 _323_ (
    .A(_121_),
    .B(_122_),
    .Y(pop_data[9])
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(\fifo_mem[3] [8]),
    .B(_013_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a222oi_1 _325_ (
    .A1(\fifo_mem[0] [8]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [8]),
    .C1(_014_),
    .C2(\fifo_mem[2] [8]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand2_1 _326_ (
    .A(_123_),
    .B(_124_),
    .Y(pop_data[8])
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(\fifo_mem[3] [7]),
    .B(_013_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a222oi_1 _328_ (
    .A1(\fifo_mem[0] [7]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [7]),
    .C1(_014_),
    .C2(\fifo_mem[2] [7]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(_125_),
    .B(_126_),
    .Y(pop_data[7])
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(\fifo_mem[1] [6]),
    .B(_012_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a222oi_1 _331_ (
    .A1(\fifo_mem[0] [6]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [6]),
    .C1(_014_),
    .C2(\fifo_mem[2] [6]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _332_ (
    .A(_127_),
    .B(_128_),
    .Y(pop_data[6])
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(\fifo_mem[3] [5]),
    .B(_013_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a222oi_1 _334_ (
    .A1(\fifo_mem[0] [5]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [5]),
    .C1(_014_),
    .C2(\fifo_mem[2] [5]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(_129_),
    .B(_130_),
    .Y(pop_data[5])
  );
  sky130_fd_sc_hd__nand2_1 _336_ (
    .A(\fifo_mem[1] [4]),
    .B(_012_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a222oi_1 _337_ (
    .A1(\fifo_mem[0] [4]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [4]),
    .C1(_014_),
    .C2(\fifo_mem[2] [4]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(_131_),
    .B(_132_),
    .Y(pop_data[4])
  );
  sky130_fd_sc_hd__nand2_1 _339_ (
    .A(\fifo_mem[3] [3]),
    .B(_013_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a222oi_1 _340_ (
    .A1(\fifo_mem[0] [3]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [3]),
    .C1(_014_),
    .C2(\fifo_mem[2] [3]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _341_ (
    .A(_133_),
    .B(_134_),
    .Y(pop_data[3])
  );
  sky130_fd_sc_hd__nand2_1 _342_ (
    .A(\fifo_mem[1] [2]),
    .B(_012_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__a222oi_1 _343_ (
    .A1(\fifo_mem[0] [2]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [2]),
    .C1(_014_),
    .C2(\fifo_mem[2] [2]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(_135_),
    .B(_136_),
    .Y(pop_data[2])
  );
  sky130_fd_sc_hd__nand2_1 _345_ (
    .A(\fifo_mem[1] [1]),
    .B(_012_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a222oi_1 _346_ (
    .A1(\fifo_mem[0] [1]),
    .A2(_011_),
    .B1(_013_),
    .B2(\fifo_mem[3] [1]),
    .C1(_014_),
    .C2(\fifo_mem[2] [1]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(_137_),
    .B(_138_),
    .Y(pop_data[1])
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(\fifo_mem[3] [0]),
    .B(_013_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a222oi_1 _349_ (
    .A1(\fifo_mem[0] [0]),
    .A2(_011_),
    .B1(_012_),
    .B2(\fifo_mem[1] [0]),
    .C1(_014_),
    .C2(\fifo_mem[2] [0]),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _350_ (
    .A(_139_),
    .B(_140_),
    .Y(pop_data[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _351_ (
    .A(push_valid),
    .SLEEP(occupancy[2]),
    .X(_141_)
  );
  sky130_fd_sc_hd__nand2b_1 _352_ (
    .A_N(occupancy[2]),
    .B(push_valid),
    .Y(_142_)
  );
  sky130_fd_sc_hd__xnor2_1 _353_ (
    .A(wr_ptr[0]),
    .B(_142_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(occupancy[1]),
    .B(occupancy[0]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nor3_1 _355_ (
    .A(occupancy[2]),
    .B(occupancy[1]),
    .C(occupancy[0]),
    .Y(empty)
  );
  sky130_fd_sc_hd__clkinv_1 _356_ (
    .A(empty),
    .Y(pop_valid)
  );
  sky130_fd_sc_hd__o31a_1 _357_ (
    .A1(occupancy[2]),
    .A2(occupancy[1]),
    .A3(occupancy[0]),
    .B1(pop_ready),
    .X(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _358_ (
    .A(_142_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__xnor2_1 _359_ (
    .A(_141_),
    .B(_144_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__and2_0 _360_ (
    .A(occupancy[1]),
    .B(occupancy[0]),
    .X(_147_)
  );
  sky130_fd_sc_hd__nor4_1 _361_ (
    .A(pop_ready),
    .B(_142_),
    .C(_143_),
    .D(_147_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__o211a_1 _362_ (
    .A1(_143_),
    .A2(_147_),
    .B1(_144_),
    .C1(_142_),
    .X(_149_)
  );
  sky130_fd_sc_hd__a211o_1 _363_ (
    .A1(occupancy[1]),
    .A2(_146_),
    .B1(_148_),
    .C1(_149_),
    .X(_005_)
  );
  sky130_fd_sc_hd__xnor2_1 _364_ (
    .A(occupancy[0]),
    .B(_146_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(rd_ptr[0]),
    .B(_144_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__xor2_1 _366_ (
    .A(rd_ptr[0]),
    .B(_144_),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _367_ (
    .A(rst_n),
    .B(_141_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor3b_1 _368_ (
    .A(_151_),
    .B(wr_ptr[1]),
    .C_N(wr_ptr[0]),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _369_ (
    .A(wr_ptr[0]),
    .B(_141_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nand2_1 _370_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .Y(_153_)
  );
  sky130_fd_sc_hd__xnor2_1 _371_ (
    .A(wr_ptr[1]),
    .B(_152_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _372_ (
    .A(pop_ready),
    .B(_143_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _373_ (
    .A1(_145_),
    .A2(_147_),
    .B1(_154_),
    .B2(occupancy[2]),
    .X(_009_)
  );
  sky130_fd_sc_hd__xnor2_1 _374_ (
    .A(rd_ptr[1]),
    .B(_150_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nor3_1 _375_ (
    .A(wr_ptr[1]),
    .B(wr_ptr[0]),
    .C(_151_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _376_ (
    .A(_151_),
    .B(_153_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(\fifo_mem[0] [63]),
    .B(_011_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a222oi_1 _378_ (
    .A1(\fifo_mem[1] [63]),
    .A2(_012_),
    .B1(_013_),
    .B2(\fifo_mem[3] [63]),
    .C1(_014_),
    .C2(\fifo_mem[2] [63]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nand2_1 _379_ (
    .A(_155_),
    .B(_156_),
    .Y(pop_data[63])
  );
  sky130_fd_sc_hd__nor3b_1 _380_ (
    .A(wr_ptr[0]),
    .B(_151_),
    .C_N(wr_ptr[1]),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _381_ (
    .A(push_ready),
    .B(occupancy[1]),
    .C(occupancy[0]),
    .Y(full)
  );
  sky130_fd_sc_hd__dfrtp_1 _382_ (
    .CLK(clk),
    .D(_007_),
    .Q(rd_ptr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _383_ (
    .CLK(clk),
    .D(_010_),
    .Q(rd_ptr[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _384_ (
    .CLK(clk),
    .D(_006_),
    .Q(occupancy[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _385_ (
    .CLK(clk),
    .D(_005_),
    .Q(occupancy[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _386_ (
    .CLK(clk),
    .D(_009_),
    .Q(occupancy[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _387_ (
    .CLK(clk),
    .D(_004_),
    .Q(wr_ptr[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 _388_ (
    .CLK(clk),
    .D(_008_),
    .Q(wr_ptr[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__edfxtp_1 _389_ (
    .CLK(clk),
    .D(push_data[0]),
    .DE(_003_),
    .Q(\fifo_mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _390_ (
    .CLK(clk),
    .D(push_data[1]),
    .DE(_003_),
    .Q(\fifo_mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _391_ (
    .CLK(clk),
    .D(push_data[2]),
    .DE(_003_),
    .Q(\fifo_mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _392_ (
    .CLK(clk),
    .D(push_data[3]),
    .DE(_003_),
    .Q(\fifo_mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _393_ (
    .CLK(clk),
    .D(push_data[4]),
    .DE(_003_),
    .Q(\fifo_mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _394_ (
    .CLK(clk),
    .D(push_data[5]),
    .DE(_003_),
    .Q(\fifo_mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _395_ (
    .CLK(clk),
    .D(push_data[6]),
    .DE(_003_),
    .Q(\fifo_mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _396_ (
    .CLK(clk),
    .D(push_data[7]),
    .DE(_003_),
    .Q(\fifo_mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _397_ (
    .CLK(clk),
    .D(push_data[8]),
    .DE(_003_),
    .Q(\fifo_mem[1] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _398_ (
    .CLK(clk),
    .D(push_data[9]),
    .DE(_003_),
    .Q(\fifo_mem[1] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _399_ (
    .CLK(clk),
    .D(push_data[10]),
    .DE(_003_),
    .Q(\fifo_mem[1] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _400_ (
    .CLK(clk),
    .D(push_data[11]),
    .DE(_003_),
    .Q(\fifo_mem[1] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _401_ (
    .CLK(clk),
    .D(push_data[12]),
    .DE(_003_),
    .Q(\fifo_mem[1] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _402_ (
    .CLK(clk),
    .D(push_data[13]),
    .DE(_003_),
    .Q(\fifo_mem[1] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _403_ (
    .CLK(clk),
    .D(push_data[14]),
    .DE(_003_),
    .Q(\fifo_mem[1] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _404_ (
    .CLK(clk),
    .D(push_data[15]),
    .DE(_003_),
    .Q(\fifo_mem[1] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _405_ (
    .CLK(clk),
    .D(push_data[16]),
    .DE(_003_),
    .Q(\fifo_mem[1] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _406_ (
    .CLK(clk),
    .D(push_data[17]),
    .DE(_003_),
    .Q(\fifo_mem[1] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _407_ (
    .CLK(clk),
    .D(push_data[18]),
    .DE(_003_),
    .Q(\fifo_mem[1] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _408_ (
    .CLK(clk),
    .D(push_data[19]),
    .DE(_003_),
    .Q(\fifo_mem[1] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _409_ (
    .CLK(clk),
    .D(push_data[20]),
    .DE(_003_),
    .Q(\fifo_mem[1] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _410_ (
    .CLK(clk),
    .D(push_data[21]),
    .DE(_003_),
    .Q(\fifo_mem[1] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _411_ (
    .CLK(clk),
    .D(push_data[22]),
    .DE(_003_),
    .Q(\fifo_mem[1] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _412_ (
    .CLK(clk),
    .D(push_data[23]),
    .DE(_003_),
    .Q(\fifo_mem[1] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _413_ (
    .CLK(clk),
    .D(push_data[24]),
    .DE(_003_),
    .Q(\fifo_mem[1] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _414_ (
    .CLK(clk),
    .D(push_data[25]),
    .DE(_003_),
    .Q(\fifo_mem[1] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _415_ (
    .CLK(clk),
    .D(push_data[26]),
    .DE(_003_),
    .Q(\fifo_mem[1] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _416_ (
    .CLK(clk),
    .D(push_data[27]),
    .DE(_003_),
    .Q(\fifo_mem[1] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _417_ (
    .CLK(clk),
    .D(push_data[28]),
    .DE(_003_),
    .Q(\fifo_mem[1] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _418_ (
    .CLK(clk),
    .D(push_data[29]),
    .DE(_003_),
    .Q(\fifo_mem[1] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _419_ (
    .CLK(clk),
    .D(push_data[30]),
    .DE(_003_),
    .Q(\fifo_mem[1] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _420_ (
    .CLK(clk),
    .D(push_data[31]),
    .DE(_003_),
    .Q(\fifo_mem[1] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _421_ (
    .CLK(clk),
    .D(push_data[32]),
    .DE(_003_),
    .Q(\fifo_mem[1] [32])
  );
  sky130_fd_sc_hd__edfxtp_1 _422_ (
    .CLK(clk),
    .D(push_data[33]),
    .DE(_003_),
    .Q(\fifo_mem[1] [33])
  );
  sky130_fd_sc_hd__edfxtp_1 _423_ (
    .CLK(clk),
    .D(push_data[34]),
    .DE(_003_),
    .Q(\fifo_mem[1] [34])
  );
  sky130_fd_sc_hd__edfxtp_1 _424_ (
    .CLK(clk),
    .D(push_data[35]),
    .DE(_003_),
    .Q(\fifo_mem[1] [35])
  );
  sky130_fd_sc_hd__edfxtp_1 _425_ (
    .CLK(clk),
    .D(push_data[36]),
    .DE(_003_),
    .Q(\fifo_mem[1] [36])
  );
  sky130_fd_sc_hd__edfxtp_1 _426_ (
    .CLK(clk),
    .D(push_data[37]),
    .DE(_003_),
    .Q(\fifo_mem[1] [37])
  );
  sky130_fd_sc_hd__edfxtp_1 _427_ (
    .CLK(clk),
    .D(push_data[38]),
    .DE(_003_),
    .Q(\fifo_mem[1] [38])
  );
  sky130_fd_sc_hd__edfxtp_1 _428_ (
    .CLK(clk),
    .D(push_data[39]),
    .DE(_003_),
    .Q(\fifo_mem[1] [39])
  );
  sky130_fd_sc_hd__edfxtp_1 _429_ (
    .CLK(clk),
    .D(push_data[40]),
    .DE(_003_),
    .Q(\fifo_mem[1] [40])
  );
  sky130_fd_sc_hd__edfxtp_1 _430_ (
    .CLK(clk),
    .D(push_data[41]),
    .DE(_003_),
    .Q(\fifo_mem[1] [41])
  );
  sky130_fd_sc_hd__edfxtp_1 _431_ (
    .CLK(clk),
    .D(push_data[42]),
    .DE(_003_),
    .Q(\fifo_mem[1] [42])
  );
  sky130_fd_sc_hd__edfxtp_1 _432_ (
    .CLK(clk),
    .D(push_data[43]),
    .DE(_003_),
    .Q(\fifo_mem[1] [43])
  );
  sky130_fd_sc_hd__edfxtp_1 _433_ (
    .CLK(clk),
    .D(push_data[44]),
    .DE(_003_),
    .Q(\fifo_mem[1] [44])
  );
  sky130_fd_sc_hd__edfxtp_1 _434_ (
    .CLK(clk),
    .D(push_data[45]),
    .DE(_003_),
    .Q(\fifo_mem[1] [45])
  );
  sky130_fd_sc_hd__edfxtp_1 _435_ (
    .CLK(clk),
    .D(push_data[46]),
    .DE(_003_),
    .Q(\fifo_mem[1] [46])
  );
  sky130_fd_sc_hd__edfxtp_1 _436_ (
    .CLK(clk),
    .D(push_data[47]),
    .DE(_003_),
    .Q(\fifo_mem[1] [47])
  );
  sky130_fd_sc_hd__edfxtp_1 _437_ (
    .CLK(clk),
    .D(push_data[48]),
    .DE(_003_),
    .Q(\fifo_mem[1] [48])
  );
  sky130_fd_sc_hd__edfxtp_1 _438_ (
    .CLK(clk),
    .D(push_data[49]),
    .DE(_003_),
    .Q(\fifo_mem[1] [49])
  );
  sky130_fd_sc_hd__edfxtp_1 _439_ (
    .CLK(clk),
    .D(push_data[50]),
    .DE(_003_),
    .Q(\fifo_mem[1] [50])
  );
  sky130_fd_sc_hd__edfxtp_1 _440_ (
    .CLK(clk),
    .D(push_data[51]),
    .DE(_003_),
    .Q(\fifo_mem[1] [51])
  );
  sky130_fd_sc_hd__edfxtp_1 _441_ (
    .CLK(clk),
    .D(push_data[52]),
    .DE(_003_),
    .Q(\fifo_mem[1] [52])
  );
  sky130_fd_sc_hd__edfxtp_1 _442_ (
    .CLK(clk),
    .D(push_data[53]),
    .DE(_003_),
    .Q(\fifo_mem[1] [53])
  );
  sky130_fd_sc_hd__edfxtp_1 _443_ (
    .CLK(clk),
    .D(push_data[54]),
    .DE(_003_),
    .Q(\fifo_mem[1] [54])
  );
  sky130_fd_sc_hd__edfxtp_1 _444_ (
    .CLK(clk),
    .D(push_data[55]),
    .DE(_003_),
    .Q(\fifo_mem[1] [55])
  );
  sky130_fd_sc_hd__edfxtp_1 _445_ (
    .CLK(clk),
    .D(push_data[56]),
    .DE(_003_),
    .Q(\fifo_mem[1] [56])
  );
  sky130_fd_sc_hd__edfxtp_1 _446_ (
    .CLK(clk),
    .D(push_data[57]),
    .DE(_003_),
    .Q(\fifo_mem[1] [57])
  );
  sky130_fd_sc_hd__edfxtp_1 _447_ (
    .CLK(clk),
    .D(push_data[58]),
    .DE(_003_),
    .Q(\fifo_mem[1] [58])
  );
  sky130_fd_sc_hd__edfxtp_1 _448_ (
    .CLK(clk),
    .D(push_data[59]),
    .DE(_003_),
    .Q(\fifo_mem[1] [59])
  );
  sky130_fd_sc_hd__edfxtp_1 _449_ (
    .CLK(clk),
    .D(push_data[60]),
    .DE(_003_),
    .Q(\fifo_mem[1] [60])
  );
  sky130_fd_sc_hd__edfxtp_1 _450_ (
    .CLK(clk),
    .D(push_data[61]),
    .DE(_003_),
    .Q(\fifo_mem[1] [61])
  );
  sky130_fd_sc_hd__edfxtp_1 _451_ (
    .CLK(clk),
    .D(push_data[62]),
    .DE(_003_),
    .Q(\fifo_mem[1] [62])
  );
  sky130_fd_sc_hd__edfxtp_1 _452_ (
    .CLK(clk),
    .D(push_data[63]),
    .DE(_003_),
    .Q(\fifo_mem[1] [63])
  );
  sky130_fd_sc_hd__edfxtp_1 _453_ (
    .CLK(clk),
    .D(push_data[0]),
    .DE(_002_),
    .Q(\fifo_mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _454_ (
    .CLK(clk),
    .D(push_data[1]),
    .DE(_002_),
    .Q(\fifo_mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _455_ (
    .CLK(clk),
    .D(push_data[2]),
    .DE(_002_),
    .Q(\fifo_mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _456_ (
    .CLK(clk),
    .D(push_data[3]),
    .DE(_002_),
    .Q(\fifo_mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _457_ (
    .CLK(clk),
    .D(push_data[4]),
    .DE(_002_),
    .Q(\fifo_mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _458_ (
    .CLK(clk),
    .D(push_data[5]),
    .DE(_002_),
    .Q(\fifo_mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _459_ (
    .CLK(clk),
    .D(push_data[6]),
    .DE(_002_),
    .Q(\fifo_mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _460_ (
    .CLK(clk),
    .D(push_data[7]),
    .DE(_002_),
    .Q(\fifo_mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _461_ (
    .CLK(clk),
    .D(push_data[8]),
    .DE(_002_),
    .Q(\fifo_mem[2] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _462_ (
    .CLK(clk),
    .D(push_data[9]),
    .DE(_002_),
    .Q(\fifo_mem[2] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _463_ (
    .CLK(clk),
    .D(push_data[10]),
    .DE(_002_),
    .Q(\fifo_mem[2] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _464_ (
    .CLK(clk),
    .D(push_data[11]),
    .DE(_002_),
    .Q(\fifo_mem[2] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _465_ (
    .CLK(clk),
    .D(push_data[12]),
    .DE(_002_),
    .Q(\fifo_mem[2] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _466_ (
    .CLK(clk),
    .D(push_data[13]),
    .DE(_002_),
    .Q(\fifo_mem[2] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _467_ (
    .CLK(clk),
    .D(push_data[14]),
    .DE(_002_),
    .Q(\fifo_mem[2] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _468_ (
    .CLK(clk),
    .D(push_data[15]),
    .DE(_002_),
    .Q(\fifo_mem[2] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _469_ (
    .CLK(clk),
    .D(push_data[16]),
    .DE(_002_),
    .Q(\fifo_mem[2] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _470_ (
    .CLK(clk),
    .D(push_data[17]),
    .DE(_002_),
    .Q(\fifo_mem[2] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _471_ (
    .CLK(clk),
    .D(push_data[18]),
    .DE(_002_),
    .Q(\fifo_mem[2] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _472_ (
    .CLK(clk),
    .D(push_data[19]),
    .DE(_002_),
    .Q(\fifo_mem[2] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _473_ (
    .CLK(clk),
    .D(push_data[20]),
    .DE(_002_),
    .Q(\fifo_mem[2] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _474_ (
    .CLK(clk),
    .D(push_data[21]),
    .DE(_002_),
    .Q(\fifo_mem[2] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _475_ (
    .CLK(clk),
    .D(push_data[22]),
    .DE(_002_),
    .Q(\fifo_mem[2] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _476_ (
    .CLK(clk),
    .D(push_data[23]),
    .DE(_002_),
    .Q(\fifo_mem[2] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _477_ (
    .CLK(clk),
    .D(push_data[24]),
    .DE(_002_),
    .Q(\fifo_mem[2] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _478_ (
    .CLK(clk),
    .D(push_data[25]),
    .DE(_002_),
    .Q(\fifo_mem[2] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _479_ (
    .CLK(clk),
    .D(push_data[26]),
    .DE(_002_),
    .Q(\fifo_mem[2] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _480_ (
    .CLK(clk),
    .D(push_data[27]),
    .DE(_002_),
    .Q(\fifo_mem[2] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _481_ (
    .CLK(clk),
    .D(push_data[28]),
    .DE(_002_),
    .Q(\fifo_mem[2] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _482_ (
    .CLK(clk),
    .D(push_data[29]),
    .DE(_002_),
    .Q(\fifo_mem[2] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _483_ (
    .CLK(clk),
    .D(push_data[30]),
    .DE(_002_),
    .Q(\fifo_mem[2] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _484_ (
    .CLK(clk),
    .D(push_data[31]),
    .DE(_002_),
    .Q(\fifo_mem[2] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _485_ (
    .CLK(clk),
    .D(push_data[32]),
    .DE(_002_),
    .Q(\fifo_mem[2] [32])
  );
  sky130_fd_sc_hd__edfxtp_1 _486_ (
    .CLK(clk),
    .D(push_data[33]),
    .DE(_002_),
    .Q(\fifo_mem[2] [33])
  );
  sky130_fd_sc_hd__edfxtp_1 _487_ (
    .CLK(clk),
    .D(push_data[34]),
    .DE(_002_),
    .Q(\fifo_mem[2] [34])
  );
  sky130_fd_sc_hd__edfxtp_1 _488_ (
    .CLK(clk),
    .D(push_data[35]),
    .DE(_002_),
    .Q(\fifo_mem[2] [35])
  );
  sky130_fd_sc_hd__edfxtp_1 _489_ (
    .CLK(clk),
    .D(push_data[36]),
    .DE(_002_),
    .Q(\fifo_mem[2] [36])
  );
  sky130_fd_sc_hd__edfxtp_1 _490_ (
    .CLK(clk),
    .D(push_data[37]),
    .DE(_002_),
    .Q(\fifo_mem[2] [37])
  );
  sky130_fd_sc_hd__edfxtp_1 _491_ (
    .CLK(clk),
    .D(push_data[38]),
    .DE(_002_),
    .Q(\fifo_mem[2] [38])
  );
  sky130_fd_sc_hd__edfxtp_1 _492_ (
    .CLK(clk),
    .D(push_data[39]),
    .DE(_002_),
    .Q(\fifo_mem[2] [39])
  );
  sky130_fd_sc_hd__edfxtp_1 _493_ (
    .CLK(clk),
    .D(push_data[40]),
    .DE(_002_),
    .Q(\fifo_mem[2] [40])
  );
  sky130_fd_sc_hd__edfxtp_1 _494_ (
    .CLK(clk),
    .D(push_data[41]),
    .DE(_002_),
    .Q(\fifo_mem[2] [41])
  );
  sky130_fd_sc_hd__edfxtp_1 _495_ (
    .CLK(clk),
    .D(push_data[42]),
    .DE(_002_),
    .Q(\fifo_mem[2] [42])
  );
  sky130_fd_sc_hd__edfxtp_1 _496_ (
    .CLK(clk),
    .D(push_data[43]),
    .DE(_002_),
    .Q(\fifo_mem[2] [43])
  );
  sky130_fd_sc_hd__edfxtp_1 _497_ (
    .CLK(clk),
    .D(push_data[44]),
    .DE(_002_),
    .Q(\fifo_mem[2] [44])
  );
  sky130_fd_sc_hd__edfxtp_1 _498_ (
    .CLK(clk),
    .D(push_data[45]),
    .DE(_002_),
    .Q(\fifo_mem[2] [45])
  );
  sky130_fd_sc_hd__edfxtp_1 _499_ (
    .CLK(clk),
    .D(push_data[46]),
    .DE(_002_),
    .Q(\fifo_mem[2] [46])
  );
  sky130_fd_sc_hd__edfxtp_1 _500_ (
    .CLK(clk),
    .D(push_data[47]),
    .DE(_002_),
    .Q(\fifo_mem[2] [47])
  );
  sky130_fd_sc_hd__edfxtp_1 _501_ (
    .CLK(clk),
    .D(push_data[48]),
    .DE(_002_),
    .Q(\fifo_mem[2] [48])
  );
  sky130_fd_sc_hd__edfxtp_1 _502_ (
    .CLK(clk),
    .D(push_data[49]),
    .DE(_002_),
    .Q(\fifo_mem[2] [49])
  );
  sky130_fd_sc_hd__edfxtp_1 _503_ (
    .CLK(clk),
    .D(push_data[50]),
    .DE(_002_),
    .Q(\fifo_mem[2] [50])
  );
  sky130_fd_sc_hd__edfxtp_1 _504_ (
    .CLK(clk),
    .D(push_data[51]),
    .DE(_002_),
    .Q(\fifo_mem[2] [51])
  );
  sky130_fd_sc_hd__edfxtp_1 _505_ (
    .CLK(clk),
    .D(push_data[52]),
    .DE(_002_),
    .Q(\fifo_mem[2] [52])
  );
  sky130_fd_sc_hd__edfxtp_1 _506_ (
    .CLK(clk),
    .D(push_data[53]),
    .DE(_002_),
    .Q(\fifo_mem[2] [53])
  );
  sky130_fd_sc_hd__edfxtp_1 _507_ (
    .CLK(clk),
    .D(push_data[54]),
    .DE(_002_),
    .Q(\fifo_mem[2] [54])
  );
  sky130_fd_sc_hd__edfxtp_1 _508_ (
    .CLK(clk),
    .D(push_data[55]),
    .DE(_002_),
    .Q(\fifo_mem[2] [55])
  );
  sky130_fd_sc_hd__edfxtp_1 _509_ (
    .CLK(clk),
    .D(push_data[56]),
    .DE(_002_),
    .Q(\fifo_mem[2] [56])
  );
  sky130_fd_sc_hd__edfxtp_1 _510_ (
    .CLK(clk),
    .D(push_data[57]),
    .DE(_002_),
    .Q(\fifo_mem[2] [57])
  );
  sky130_fd_sc_hd__edfxtp_1 _511_ (
    .CLK(clk),
    .D(push_data[58]),
    .DE(_002_),
    .Q(\fifo_mem[2] [58])
  );
  sky130_fd_sc_hd__edfxtp_1 _512_ (
    .CLK(clk),
    .D(push_data[59]),
    .DE(_002_),
    .Q(\fifo_mem[2] [59])
  );
  sky130_fd_sc_hd__edfxtp_1 _513_ (
    .CLK(clk),
    .D(push_data[60]),
    .DE(_002_),
    .Q(\fifo_mem[2] [60])
  );
  sky130_fd_sc_hd__edfxtp_1 _514_ (
    .CLK(clk),
    .D(push_data[61]),
    .DE(_002_),
    .Q(\fifo_mem[2] [61])
  );
  sky130_fd_sc_hd__edfxtp_1 _515_ (
    .CLK(clk),
    .D(push_data[62]),
    .DE(_002_),
    .Q(\fifo_mem[2] [62])
  );
  sky130_fd_sc_hd__edfxtp_1 _516_ (
    .CLK(clk),
    .D(push_data[63]),
    .DE(_002_),
    .Q(\fifo_mem[2] [63])
  );
  sky130_fd_sc_hd__edfxtp_1 _517_ (
    .CLK(clk),
    .D(push_data[0]),
    .DE(_001_),
    .Q(\fifo_mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _518_ (
    .CLK(clk),
    .D(push_data[1]),
    .DE(_001_),
    .Q(\fifo_mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _519_ (
    .CLK(clk),
    .D(push_data[2]),
    .DE(_001_),
    .Q(\fifo_mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _520_ (
    .CLK(clk),
    .D(push_data[3]),
    .DE(_001_),
    .Q(\fifo_mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _521_ (
    .CLK(clk),
    .D(push_data[4]),
    .DE(_001_),
    .Q(\fifo_mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _522_ (
    .CLK(clk),
    .D(push_data[5]),
    .DE(_001_),
    .Q(\fifo_mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _523_ (
    .CLK(clk),
    .D(push_data[6]),
    .DE(_001_),
    .Q(\fifo_mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _524_ (
    .CLK(clk),
    .D(push_data[7]),
    .DE(_001_),
    .Q(\fifo_mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _525_ (
    .CLK(clk),
    .D(push_data[8]),
    .DE(_001_),
    .Q(\fifo_mem[3] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _526_ (
    .CLK(clk),
    .D(push_data[9]),
    .DE(_001_),
    .Q(\fifo_mem[3] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _527_ (
    .CLK(clk),
    .D(push_data[10]),
    .DE(_001_),
    .Q(\fifo_mem[3] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _528_ (
    .CLK(clk),
    .D(push_data[11]),
    .DE(_001_),
    .Q(\fifo_mem[3] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _529_ (
    .CLK(clk),
    .D(push_data[12]),
    .DE(_001_),
    .Q(\fifo_mem[3] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _530_ (
    .CLK(clk),
    .D(push_data[13]),
    .DE(_001_),
    .Q(\fifo_mem[3] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _531_ (
    .CLK(clk),
    .D(push_data[14]),
    .DE(_001_),
    .Q(\fifo_mem[3] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _532_ (
    .CLK(clk),
    .D(push_data[15]),
    .DE(_001_),
    .Q(\fifo_mem[3] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _533_ (
    .CLK(clk),
    .D(push_data[16]),
    .DE(_001_),
    .Q(\fifo_mem[3] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _534_ (
    .CLK(clk),
    .D(push_data[17]),
    .DE(_001_),
    .Q(\fifo_mem[3] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _535_ (
    .CLK(clk),
    .D(push_data[18]),
    .DE(_001_),
    .Q(\fifo_mem[3] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _536_ (
    .CLK(clk),
    .D(push_data[19]),
    .DE(_001_),
    .Q(\fifo_mem[3] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _537_ (
    .CLK(clk),
    .D(push_data[20]),
    .DE(_001_),
    .Q(\fifo_mem[3] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _538_ (
    .CLK(clk),
    .D(push_data[21]),
    .DE(_001_),
    .Q(\fifo_mem[3] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _539_ (
    .CLK(clk),
    .D(push_data[22]),
    .DE(_001_),
    .Q(\fifo_mem[3] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _540_ (
    .CLK(clk),
    .D(push_data[23]),
    .DE(_001_),
    .Q(\fifo_mem[3] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _541_ (
    .CLK(clk),
    .D(push_data[24]),
    .DE(_001_),
    .Q(\fifo_mem[3] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _542_ (
    .CLK(clk),
    .D(push_data[25]),
    .DE(_001_),
    .Q(\fifo_mem[3] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _543_ (
    .CLK(clk),
    .D(push_data[26]),
    .DE(_001_),
    .Q(\fifo_mem[3] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _544_ (
    .CLK(clk),
    .D(push_data[27]),
    .DE(_001_),
    .Q(\fifo_mem[3] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _545_ (
    .CLK(clk),
    .D(push_data[28]),
    .DE(_001_),
    .Q(\fifo_mem[3] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _546_ (
    .CLK(clk),
    .D(push_data[29]),
    .DE(_001_),
    .Q(\fifo_mem[3] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _547_ (
    .CLK(clk),
    .D(push_data[30]),
    .DE(_001_),
    .Q(\fifo_mem[3] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _548_ (
    .CLK(clk),
    .D(push_data[31]),
    .DE(_001_),
    .Q(\fifo_mem[3] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _549_ (
    .CLK(clk),
    .D(push_data[32]),
    .DE(_001_),
    .Q(\fifo_mem[3] [32])
  );
  sky130_fd_sc_hd__edfxtp_1 _550_ (
    .CLK(clk),
    .D(push_data[33]),
    .DE(_001_),
    .Q(\fifo_mem[3] [33])
  );
  sky130_fd_sc_hd__edfxtp_1 _551_ (
    .CLK(clk),
    .D(push_data[34]),
    .DE(_001_),
    .Q(\fifo_mem[3] [34])
  );
  sky130_fd_sc_hd__edfxtp_1 _552_ (
    .CLK(clk),
    .D(push_data[35]),
    .DE(_001_),
    .Q(\fifo_mem[3] [35])
  );
  sky130_fd_sc_hd__edfxtp_1 _553_ (
    .CLK(clk),
    .D(push_data[36]),
    .DE(_001_),
    .Q(\fifo_mem[3] [36])
  );
  sky130_fd_sc_hd__edfxtp_1 _554_ (
    .CLK(clk),
    .D(push_data[37]),
    .DE(_001_),
    .Q(\fifo_mem[3] [37])
  );
  sky130_fd_sc_hd__edfxtp_1 _555_ (
    .CLK(clk),
    .D(push_data[38]),
    .DE(_001_),
    .Q(\fifo_mem[3] [38])
  );
  sky130_fd_sc_hd__edfxtp_1 _556_ (
    .CLK(clk),
    .D(push_data[39]),
    .DE(_001_),
    .Q(\fifo_mem[3] [39])
  );
  sky130_fd_sc_hd__edfxtp_1 _557_ (
    .CLK(clk),
    .D(push_data[40]),
    .DE(_001_),
    .Q(\fifo_mem[3] [40])
  );
  sky130_fd_sc_hd__edfxtp_1 _558_ (
    .CLK(clk),
    .D(push_data[41]),
    .DE(_001_),
    .Q(\fifo_mem[3] [41])
  );
  sky130_fd_sc_hd__edfxtp_1 _559_ (
    .CLK(clk),
    .D(push_data[42]),
    .DE(_001_),
    .Q(\fifo_mem[3] [42])
  );
  sky130_fd_sc_hd__edfxtp_1 _560_ (
    .CLK(clk),
    .D(push_data[43]),
    .DE(_001_),
    .Q(\fifo_mem[3] [43])
  );
  sky130_fd_sc_hd__edfxtp_1 _561_ (
    .CLK(clk),
    .D(push_data[44]),
    .DE(_001_),
    .Q(\fifo_mem[3] [44])
  );
  sky130_fd_sc_hd__edfxtp_1 _562_ (
    .CLK(clk),
    .D(push_data[45]),
    .DE(_001_),
    .Q(\fifo_mem[3] [45])
  );
  sky130_fd_sc_hd__edfxtp_1 _563_ (
    .CLK(clk),
    .D(push_data[46]),
    .DE(_001_),
    .Q(\fifo_mem[3] [46])
  );
  sky130_fd_sc_hd__edfxtp_1 _564_ (
    .CLK(clk),
    .D(push_data[47]),
    .DE(_001_),
    .Q(\fifo_mem[3] [47])
  );
  sky130_fd_sc_hd__edfxtp_1 _565_ (
    .CLK(clk),
    .D(push_data[48]),
    .DE(_001_),
    .Q(\fifo_mem[3] [48])
  );
  sky130_fd_sc_hd__edfxtp_1 _566_ (
    .CLK(clk),
    .D(push_data[49]),
    .DE(_001_),
    .Q(\fifo_mem[3] [49])
  );
  sky130_fd_sc_hd__edfxtp_1 _567_ (
    .CLK(clk),
    .D(push_data[50]),
    .DE(_001_),
    .Q(\fifo_mem[3] [50])
  );
  sky130_fd_sc_hd__edfxtp_1 _568_ (
    .CLK(clk),
    .D(push_data[51]),
    .DE(_001_),
    .Q(\fifo_mem[3] [51])
  );
  sky130_fd_sc_hd__edfxtp_1 _569_ (
    .CLK(clk),
    .D(push_data[52]),
    .DE(_001_),
    .Q(\fifo_mem[3] [52])
  );
  sky130_fd_sc_hd__edfxtp_1 _570_ (
    .CLK(clk),
    .D(push_data[53]),
    .DE(_001_),
    .Q(\fifo_mem[3] [53])
  );
  sky130_fd_sc_hd__edfxtp_1 _571_ (
    .CLK(clk),
    .D(push_data[54]),
    .DE(_001_),
    .Q(\fifo_mem[3] [54])
  );
  sky130_fd_sc_hd__edfxtp_1 _572_ (
    .CLK(clk),
    .D(push_data[55]),
    .DE(_001_),
    .Q(\fifo_mem[3] [55])
  );
  sky130_fd_sc_hd__edfxtp_1 _573_ (
    .CLK(clk),
    .D(push_data[56]),
    .DE(_001_),
    .Q(\fifo_mem[3] [56])
  );
  sky130_fd_sc_hd__edfxtp_1 _574_ (
    .CLK(clk),
    .D(push_data[57]),
    .DE(_001_),
    .Q(\fifo_mem[3] [57])
  );
  sky130_fd_sc_hd__edfxtp_1 _575_ (
    .CLK(clk),
    .D(push_data[58]),
    .DE(_001_),
    .Q(\fifo_mem[3] [58])
  );
  sky130_fd_sc_hd__edfxtp_1 _576_ (
    .CLK(clk),
    .D(push_data[59]),
    .DE(_001_),
    .Q(\fifo_mem[3] [59])
  );
  sky130_fd_sc_hd__edfxtp_1 _577_ (
    .CLK(clk),
    .D(push_data[60]),
    .DE(_001_),
    .Q(\fifo_mem[3] [60])
  );
  sky130_fd_sc_hd__edfxtp_1 _578_ (
    .CLK(clk),
    .D(push_data[61]),
    .DE(_001_),
    .Q(\fifo_mem[3] [61])
  );
  sky130_fd_sc_hd__edfxtp_1 _579_ (
    .CLK(clk),
    .D(push_data[62]),
    .DE(_001_),
    .Q(\fifo_mem[3] [62])
  );
  sky130_fd_sc_hd__edfxtp_1 _580_ (
    .CLK(clk),
    .D(push_data[63]),
    .DE(_001_),
    .Q(\fifo_mem[3] [63])
  );
  sky130_fd_sc_hd__edfxtp_1 _581_ (
    .CLK(clk),
    .D(push_data[0]),
    .DE(_000_),
    .Q(\fifo_mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _582_ (
    .CLK(clk),
    .D(push_data[1]),
    .DE(_000_),
    .Q(\fifo_mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _583_ (
    .CLK(clk),
    .D(push_data[2]),
    .DE(_000_),
    .Q(\fifo_mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _584_ (
    .CLK(clk),
    .D(push_data[3]),
    .DE(_000_),
    .Q(\fifo_mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _585_ (
    .CLK(clk),
    .D(push_data[4]),
    .DE(_000_),
    .Q(\fifo_mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _586_ (
    .CLK(clk),
    .D(push_data[5]),
    .DE(_000_),
    .Q(\fifo_mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _587_ (
    .CLK(clk),
    .D(push_data[6]),
    .DE(_000_),
    .Q(\fifo_mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _588_ (
    .CLK(clk),
    .D(push_data[7]),
    .DE(_000_),
    .Q(\fifo_mem[0] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _589_ (
    .CLK(clk),
    .D(push_data[8]),
    .DE(_000_),
    .Q(\fifo_mem[0] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _590_ (
    .CLK(clk),
    .D(push_data[9]),
    .DE(_000_),
    .Q(\fifo_mem[0] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _591_ (
    .CLK(clk),
    .D(push_data[10]),
    .DE(_000_),
    .Q(\fifo_mem[0] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _592_ (
    .CLK(clk),
    .D(push_data[11]),
    .DE(_000_),
    .Q(\fifo_mem[0] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _593_ (
    .CLK(clk),
    .D(push_data[12]),
    .DE(_000_),
    .Q(\fifo_mem[0] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _594_ (
    .CLK(clk),
    .D(push_data[13]),
    .DE(_000_),
    .Q(\fifo_mem[0] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _595_ (
    .CLK(clk),
    .D(push_data[14]),
    .DE(_000_),
    .Q(\fifo_mem[0] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _596_ (
    .CLK(clk),
    .D(push_data[15]),
    .DE(_000_),
    .Q(\fifo_mem[0] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _597_ (
    .CLK(clk),
    .D(push_data[16]),
    .DE(_000_),
    .Q(\fifo_mem[0] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _598_ (
    .CLK(clk),
    .D(push_data[17]),
    .DE(_000_),
    .Q(\fifo_mem[0] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _599_ (
    .CLK(clk),
    .D(push_data[18]),
    .DE(_000_),
    .Q(\fifo_mem[0] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _600_ (
    .CLK(clk),
    .D(push_data[19]),
    .DE(_000_),
    .Q(\fifo_mem[0] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _601_ (
    .CLK(clk),
    .D(push_data[20]),
    .DE(_000_),
    .Q(\fifo_mem[0] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _602_ (
    .CLK(clk),
    .D(push_data[21]),
    .DE(_000_),
    .Q(\fifo_mem[0] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _603_ (
    .CLK(clk),
    .D(push_data[22]),
    .DE(_000_),
    .Q(\fifo_mem[0] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _604_ (
    .CLK(clk),
    .D(push_data[23]),
    .DE(_000_),
    .Q(\fifo_mem[0] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _605_ (
    .CLK(clk),
    .D(push_data[24]),
    .DE(_000_),
    .Q(\fifo_mem[0] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _606_ (
    .CLK(clk),
    .D(push_data[25]),
    .DE(_000_),
    .Q(\fifo_mem[0] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _607_ (
    .CLK(clk),
    .D(push_data[26]),
    .DE(_000_),
    .Q(\fifo_mem[0] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _608_ (
    .CLK(clk),
    .D(push_data[27]),
    .DE(_000_),
    .Q(\fifo_mem[0] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _609_ (
    .CLK(clk),
    .D(push_data[28]),
    .DE(_000_),
    .Q(\fifo_mem[0] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _610_ (
    .CLK(clk),
    .D(push_data[29]),
    .DE(_000_),
    .Q(\fifo_mem[0] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _611_ (
    .CLK(clk),
    .D(push_data[30]),
    .DE(_000_),
    .Q(\fifo_mem[0] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _612_ (
    .CLK(clk),
    .D(push_data[31]),
    .DE(_000_),
    .Q(\fifo_mem[0] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _613_ (
    .CLK(clk),
    .D(push_data[32]),
    .DE(_000_),
    .Q(\fifo_mem[0] [32])
  );
  sky130_fd_sc_hd__edfxtp_1 _614_ (
    .CLK(clk),
    .D(push_data[33]),
    .DE(_000_),
    .Q(\fifo_mem[0] [33])
  );
  sky130_fd_sc_hd__edfxtp_1 _615_ (
    .CLK(clk),
    .D(push_data[34]),
    .DE(_000_),
    .Q(\fifo_mem[0] [34])
  );
  sky130_fd_sc_hd__edfxtp_1 _616_ (
    .CLK(clk),
    .D(push_data[35]),
    .DE(_000_),
    .Q(\fifo_mem[0] [35])
  );
  sky130_fd_sc_hd__edfxtp_1 _617_ (
    .CLK(clk),
    .D(push_data[36]),
    .DE(_000_),
    .Q(\fifo_mem[0] [36])
  );
  sky130_fd_sc_hd__edfxtp_1 _618_ (
    .CLK(clk),
    .D(push_data[37]),
    .DE(_000_),
    .Q(\fifo_mem[0] [37])
  );
  sky130_fd_sc_hd__edfxtp_1 _619_ (
    .CLK(clk),
    .D(push_data[38]),
    .DE(_000_),
    .Q(\fifo_mem[0] [38])
  );
  sky130_fd_sc_hd__edfxtp_1 _620_ (
    .CLK(clk),
    .D(push_data[39]),
    .DE(_000_),
    .Q(\fifo_mem[0] [39])
  );
  sky130_fd_sc_hd__edfxtp_1 _621_ (
    .CLK(clk),
    .D(push_data[40]),
    .DE(_000_),
    .Q(\fifo_mem[0] [40])
  );
  sky130_fd_sc_hd__edfxtp_1 _622_ (
    .CLK(clk),
    .D(push_data[41]),
    .DE(_000_),
    .Q(\fifo_mem[0] [41])
  );
  sky130_fd_sc_hd__edfxtp_1 _623_ (
    .CLK(clk),
    .D(push_data[42]),
    .DE(_000_),
    .Q(\fifo_mem[0] [42])
  );
  sky130_fd_sc_hd__edfxtp_1 _624_ (
    .CLK(clk),
    .D(push_data[43]),
    .DE(_000_),
    .Q(\fifo_mem[0] [43])
  );
  sky130_fd_sc_hd__edfxtp_1 _625_ (
    .CLK(clk),
    .D(push_data[44]),
    .DE(_000_),
    .Q(\fifo_mem[0] [44])
  );
  sky130_fd_sc_hd__edfxtp_1 _626_ (
    .CLK(clk),
    .D(push_data[45]),
    .DE(_000_),
    .Q(\fifo_mem[0] [45])
  );
  sky130_fd_sc_hd__edfxtp_1 _627_ (
    .CLK(clk),
    .D(push_data[46]),
    .DE(_000_),
    .Q(\fifo_mem[0] [46])
  );
  sky130_fd_sc_hd__edfxtp_1 _628_ (
    .CLK(clk),
    .D(push_data[47]),
    .DE(_000_),
    .Q(\fifo_mem[0] [47])
  );
  sky130_fd_sc_hd__edfxtp_1 _629_ (
    .CLK(clk),
    .D(push_data[48]),
    .DE(_000_),
    .Q(\fifo_mem[0] [48])
  );
  sky130_fd_sc_hd__edfxtp_1 _630_ (
    .CLK(clk),
    .D(push_data[49]),
    .DE(_000_),
    .Q(\fifo_mem[0] [49])
  );
  sky130_fd_sc_hd__edfxtp_1 _631_ (
    .CLK(clk),
    .D(push_data[50]),
    .DE(_000_),
    .Q(\fifo_mem[0] [50])
  );
  sky130_fd_sc_hd__edfxtp_1 _632_ (
    .CLK(clk),
    .D(push_data[51]),
    .DE(_000_),
    .Q(\fifo_mem[0] [51])
  );
  sky130_fd_sc_hd__edfxtp_1 _633_ (
    .CLK(clk),
    .D(push_data[52]),
    .DE(_000_),
    .Q(\fifo_mem[0] [52])
  );
  sky130_fd_sc_hd__edfxtp_1 _634_ (
    .CLK(clk),
    .D(push_data[53]),
    .DE(_000_),
    .Q(\fifo_mem[0] [53])
  );
  sky130_fd_sc_hd__edfxtp_1 _635_ (
    .CLK(clk),
    .D(push_data[54]),
    .DE(_000_),
    .Q(\fifo_mem[0] [54])
  );
  sky130_fd_sc_hd__edfxtp_1 _636_ (
    .CLK(clk),
    .D(push_data[55]),
    .DE(_000_),
    .Q(\fifo_mem[0] [55])
  );
  sky130_fd_sc_hd__edfxtp_1 _637_ (
    .CLK(clk),
    .D(push_data[56]),
    .DE(_000_),
    .Q(\fifo_mem[0] [56])
  );
  sky130_fd_sc_hd__edfxtp_1 _638_ (
    .CLK(clk),
    .D(push_data[57]),
    .DE(_000_),
    .Q(\fifo_mem[0] [57])
  );
  sky130_fd_sc_hd__edfxtp_1 _639_ (
    .CLK(clk),
    .D(push_data[58]),
    .DE(_000_),
    .Q(\fifo_mem[0] [58])
  );
  sky130_fd_sc_hd__edfxtp_1 _640_ (
    .CLK(clk),
    .D(push_data[59]),
    .DE(_000_),
    .Q(\fifo_mem[0] [59])
  );
  sky130_fd_sc_hd__edfxtp_1 _641_ (
    .CLK(clk),
    .D(push_data[60]),
    .DE(_000_),
    .Q(\fifo_mem[0] [60])
  );
  sky130_fd_sc_hd__edfxtp_1 _642_ (
    .CLK(clk),
    .D(push_data[61]),
    .DE(_000_),
    .Q(\fifo_mem[0] [61])
  );
  sky130_fd_sc_hd__edfxtp_1 _643_ (
    .CLK(clk),
    .D(push_data[62]),
    .DE(_000_),
    .Q(\fifo_mem[0] [62])
  );
  sky130_fd_sc_hd__edfxtp_1 _644_ (
    .CLK(clk),
    .D(push_data[63]),
    .DE(_000_),
    .Q(\fifo_mem[0] [63])
  );
endmodule
